// The field AUTHORING model — what a composer UI edits before it becomes a
// schema field.
//
// This is the shape the browser's block-composer works in, shared so the App,
// the data-gateway craft and a Node runtime agree on what a field is while it
// is being authored. It is NOT the source of truth for what a field IS: that is
// the engine schema, which carries the declaration and persists it (see
// design/block-field-semantics.md). This model is what you fill in to produce
// one.
//
// Formula-based validation lives in ../validation.

// ---- Field model (mirrors block-composer/types.ts) ----------------------

export type FieldTypeEnum =
    | 'unspecified'
    | 'enum'
    | 'multiSelect'
    | 'datetime'
    | 'boolean'
    | 'string'
    | 'number'
    | 'image'
    | 'fieldRef'
    | 'multiSelectRef'

export interface EnumValue {
    id: string
    label: string
    description: string
    color: string
}

export interface FieldSetting {
    id: string
    name: string
    type: FieldTypeEnum
    description?: string
    required: boolean
    primary: boolean
    enumId?: string
    defaultValue?: string
    format?: string
    validation?: string
    unique?: boolean
    valueFormula?: string
    refSelf?: boolean
    refSheetId?: number
    refBlockId?: number
    refFieldName?: string
}

// The `required` / `unique` / membership CHECKS used to live here as a second,
// independent implementation over an injected value port. They are gone: a
// field that declares `required`, `unique`, `enum`/`multiSelect` or `fieldRef`
// now has the matching rule generated by the engine from the declaration
// (crates/controller/src/block_manager/derived_rules.rs), installed as a
// per-record validation shadow, and reported through the same channel as every
// other rule — the warning marker, `list_violations`, and the
// `overrideValidation` write gate.
//
// Two implementations of one constraint is how this area went wrong: they did
// not even agree on what "the same value" meant (`type:value` here,
// COUNTIF's stringified value in the engine), so the number 1 and the text "1"
// collided in one and not the other. See design/block-field-semantics.md §2.3.
