[package]
name = "logisheets_astchecker"
description = "Validates Excel formula AST arguments for the LogiSheets spreadsheet engine."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
logisheets_parser = { workspace = true }
logisheets_base = { workspace = true }
