[package]
authors = ["ImJeremyHe<yiliang.he@qq.com>"]
edition = "2018"
name = "sequencer"
version = "0.1.0"
description = "A server that provides LogiSheets with the ability of users' online editting"
license = "MIT"
