// A field's `FieldInfo`, built from the engine schema rather than looked up in
// the host's own store.
//
// The widget layer used to resolve `schema.fields[i].renderId` against
// `BlockManager.fieldManager` and **skip rendering the whole block** if any
// field failed to resolve. That made a host-side store, restored from an opaque
// AppData blob, a precondition for drawing a block at all — so a table
// converted from a foreign .xlsx had to be papered over with a
// `hydrateUnspecifiedFields` pass that synthesized placeholder entries on every
// render.
//
// Now the schema carries the declaration itself (see
// design/block-field-semantics.md), so there is nothing to look up: every
// schema field projects to a `FieldInfo`, always — including the field's write
// policy, which the schema declares too. The host store is gone: nothing about
// a field lives anywhere but the schema.

import type {
    BlockInfo,
    BlockSchema,
    BlockSchemaFieldEntry,
} from 'logisheets-web/pure'
import type {FieldInfo, FieldTypeEnum} from 'logisheets-engine'

/**
 * The declared type, as the widget layer's discriminated union.
 *
 * The number / date formatter is NOT part of the declaration — it is how the
 * value is drawn — so it comes from the field's render info, which is where the
 * engine keeps it.
 *
 * `validation` on the variants that carry one is the AUTHOR'S rule only. The
 * rules a declaration implies (`required`, `unique`, membership, reference
 * existence) are generated by the engine and never appear as text here; a
 * widget that wanted to show "why is this red" should read the shadow, not this
 * string.
 */
function projectType(
    f: BlockSchemaFieldEntry,
    formatter: string
): FieldTypeEnum {
    const own = f.validationFormula ?? ''
    switch (f.fieldType?.kind) {
        case 'string':
            return {type: 'string', validation: own}
        case 'number':
            return {type: 'number', validation: own, formatter}
        case 'boolean':
            return {type: 'boolean'}
        case 'datetime':
            return {type: 'datetime', formatter}
        case 'image':
            return {type: 'image'}
        case 'enum':
            return {type: 'enum', id: f.fieldType.enumSetId ?? ''}
        case 'multiSelect':
            return {type: 'multiSelect', id: f.fieldType.enumSetId ?? ''}
        case 'fieldRef':
            return {
                type: 'fieldRef',
                sheetId: f.fieldType.refSheetId ?? 0,
                blockId: f.fieldType.refBlockId ?? 0,
                fieldName: f.fieldType.refFieldName ?? '',
                validation: own,
            }
        case 'multiSelectRef':
            return {
                type: 'multiSelectRef',
                sheetId: f.fieldType.refSheetId ?? 0,
                blockId: f.fieldType.refBlockId ?? 0,
                fieldName: f.fieldType.refFieldName ?? '',
                validation: own,
            }
        default:
            // Nobody declared a type: a block from before the declaration
            // existed, or one converted from plain cells. Free-form is the
            // honest reading, and it is what the renderer already does with an
            // unspecified field.
            return {type: 'unspecified'}
    }
}

/** Project one schema field. Never fails — a schema field always has a shape. */
export function projectFieldInfo(
    info: Pick<BlockInfo, 'sheetId' | 'blockId' | 'fieldRenders'>,
    schema: Pick<BlockSchema, 'name'>,
    f: BlockSchemaFieldEntry
): FieldInfo {
    const render = info.fieldRenders.find((r) => r.renderId === f.renderId)
    return {
        id: f.renderId,
        sheetId: info.sheetId,
        blockId: info.blockId,
        refName: schema.name,
        name: f.field,
        type: projectType(f, render?.style?.formatter ?? ''),
        description: f.description ?? undefined,
        required: !!f.required,
        unique: !!f.unique,
        defaultValue: f.defaultValue ?? undefined,
        validationRaw: f.validationFormula ?? undefined,
        // From the field's DECLARED write policy. The tri-state boolean is
        // what every reader downstream already speaks, so the translation
        // happens once, here:
        //
        //   ownerOnly -> false       closed to anyone but the block's owner
        //   anyone    -> true        open, overriding the block's owner rules
        //   inherit   -> undefined   the block's own rules decide
        userEditable:
            f.writePolicy === 'ownerOnly'
                ? false
                : f.writePolicy === 'anyone'
                ? true
                : undefined,
    }
}

/** Project every field of a block, in field-axis order. */
export function projectBlockFields(
    info: Pick<BlockInfo, 'sheetId' | 'blockId' | 'fieldRenders' | 'schema'>
): FieldInfo[] {
    const schema = info.schema
    if (!schema) return []
    return [...schema.fields]
        .sort((a, b) => a.idx - b.idx)
        .map((f) => projectFieldInfo(info, schema, f))
}
