// DO NOT EDIT. CODE GENERATED BY gents.
import { StatusCode } from './status_code'
import { Task } from './task'

// `ActionEffect` represents the result of handling `EditAction`.
// `version` would be increased if the action is successfully handled.
//
// What's more, since `LogiSheets` provides developers with the ability
// of developing their own functions, in these cases, `engine` will not know
// how to compute them and just return it the JS side.
export interface ActionEffect {
    // The latest version after processing an action. 0 means latest version
    version: number
    // Tasks should be calculated outside this engine(mainly because of network limitations and customer defined)
    asyncTasks: readonly Task[]
    status: StatusCode
}
