// DO NOT EDIT. CODE GENERATED BY gents.
import {HorizontalAlignment} from './horizontal_alignment'
import {VerticalAlignment} from './vertical_alignment'

export interface Alignment {
    horizontal?: HorizontalAlignment
    vertical?: VerticalAlignment
}
