// DO NOT EDIT. CODE GENERATED BY gents.
import { Appendix } from './appendix'

export interface AppendixWithCell {
    appendix: Appendix
    sheetId: number
    blockId: number
    rowIdx: number
    colIdx: number
}
