// DO NOT EDIT. CODE GENERATED BY gents.
// Appendix is one of the craft extensions.
//
// To utilize the flexibility of cell coordinates, LogiSheets
// allows crafts to add custom metadata to cells
export interface Appendix {
    craftId: string
    tag: number
    content: string
}
