// DO NOT EDIT. CODE GENERATED BY gents.
export interface BlockInput {
    type: 'blockInput'
    sheetIdx: number
    blockId: number
    row: number
    col: number
    input: string
}

export class BlockInputBuilder {
    private _type = 'blockInput'
    private _sheetIdx!: number
    private _blockId!: number
    private _row!: number
    private _col!: number
    private _input!: string
    public sheetIdx(value: number) {
        this._sheetIdx = value
        return this
    }

    public blockId(value: number) {
        this._blockId = value
        return this
    }

    public row(value: number) {
        this._row = value
        return this
    }

    public col(value: number) {
        this._col = value
        return this
    }

    public input(value: string) {
        this._input = value
        return this
    }

    public build() {
        if (this._sheetIdx === undefined) throw new Error('missing sheetIdx')
        if (this._blockId === undefined) throw new Error('missing blockId')
        if (this._row === undefined) throw new Error('missing row')
        if (this._col === undefined) throw new Error('missing col')
        if (this._input === undefined) throw new Error('missing input')
        return {
            type: this._type,
            sheetIdx: this._sheetIdx,
            blockId: this._blockId,
            row: this._row,
            col: this._col,
            input: this._input
        }
    }
}
