// DO NOT EDIT. CODE GENERATED BY gents.
import { StyleUpdateType } from './style_update_type'

export interface BlockStyleUpdate {
    type: 'blockStyleUpdate'
    sheetIdx: number
    blockId: number
    row: number
    col: number
    styleUpdate: StyleUpdateType
}

export class BlockStyleUpdateBuilder {
    private _type = 'blockStyleUpdate'
    private _sheetIdx!: number
    private _blockId!: number
    private _row!: number
    private _col!: number
    private _styleUpdate!: StyleUpdateType
    public sheetIdx(value: number) {
        this._sheetIdx = value
        return this
    }

    public blockId(value: number) {
        this._blockId = value
        return this
    }

    public row(value: number) {
        this._row = value
        return this
    }

    public col(value: number) {
        this._col = value
        return this
    }

    public styleUpdate(value: StyleUpdateType) {
        this._styleUpdate = value
        return this
    }

    public build() {
        if (this._sheetIdx === undefined) throw new Error('missing sheetIdx')
        if (this._blockId === undefined) throw new Error('missing blockId')
        if (this._row === undefined) throw new Error('missing row')
        if (this._col === undefined) throw new Error('missing col')
        if (this._styleUpdate === undefined) {
            throw new Error('missing styleUpdate')
        }
        return {
            type: this._type,
            sheetIdx: this._sheetIdx,
            blockId: this._blockId,
            row: this._row,
            col: this._col,
            styleUpdate: this._styleUpdate
        }
    }
}
