// DO NOT EDIT. CODE GENERATED BY gents.
import {BlockInfo} from './block_info'
import {CellPosition} from './cell_position'

export interface BlockDisplayInfo {
    info: BlockInfo
    startPosition: CellPosition
    endPosition: CellPosition
}
