// DO NOT EDIT. CODE GENERATED BY gents.
import {BorderPr} from './border_pr'

export interface Border {
    left?: BorderPr
    right?: BorderPr
    top?: BorderPr
    bottom?: BorderPr
    diagonal?: BorderPr
    vertical?: BorderPr
    horizontal?: BorderPr
    diagonalUp?: boolean
    diagonalDown?: boolean
    outline: boolean
}
