// DO NOT EDIT. CODE GENERATED BY gents.

export interface CellFormatBrush {
    srcSheetIdx: number
    srcRow: number
    srcCol: number
    dstSheetIdx: number
    dstRowStart: number
    dstColStart: number
    dstRowEnd: number
    dstColEnd: number
}
