// DO NOT EDIT. CODE GENERATED BY gents.
import {StyleUpdateType} from './style_update_type'

export interface CellStyleUpdate {
    sheetIdx: number
    row: number
    col: number
    ty: StyleUpdateType
}
