// DO NOT EDIT. CODE GENERATED BY gents.
export interface CellFormatBrush {
    type: 'cellFormatBrush'
    srcSheetIdx: number
    srcRow: number
    srcCol: number
    dstSheetIdx: number
    dstRowStart: number
    dstColStart: number
    dstRowEnd: number
    dstColEnd: number
}

export class CellFormatBrushBuilder {
    private _type = 'cellFormatBrush'
    private _srcSheetIdx!: number
    private _srcRow!: number
    private _srcCol!: number
    private _dstSheetIdx!: number
    private _dstRowStart!: number
    private _dstColStart!: number
    private _dstRowEnd!: number
    private _dstColEnd!: number
    public srcSheetIdx(value: number) {
        this._srcSheetIdx = value
        return this
    }

    public srcRow(value: number) {
        this._srcRow = value
        return this
    }

    public srcCol(value: number) {
        this._srcCol = value
        return this
    }

    public dstSheetIdx(value: number) {
        this._dstSheetIdx = value
        return this
    }

    public dstRowStart(value: number) {
        this._dstRowStart = value
        return this
    }

    public dstColStart(value: number) {
        this._dstColStart = value
        return this
    }

    public dstRowEnd(value: number) {
        this._dstRowEnd = value
        return this
    }

    public dstColEnd(value: number) {
        this._dstColEnd = value
        return this
    }

    public build() {
        if (!this._srcSheetIdx) throw new Error('missing srcSheetIdx')
        if (!this._srcRow) throw new Error('missing srcRow')
        if (!this._srcCol) throw new Error('missing srcCol')
        if (!this._dstSheetIdx) throw new Error('missing dstSheetIdx')
        if (!this._dstRowStart) throw new Error('missing dstRowStart')
        if (!this._dstColStart) throw new Error('missing dstColStart')
        if (!this._dstRowEnd) throw new Error('missing dstRowEnd')
        if (!this._dstColEnd) throw new Error('missing dstColEnd')
        return {
            type: this._type,
            srcSheetIdx: this._srcSheetIdx,
            srcRow: this._srcRow,
            srcCol: this._srcCol,
            dstSheetIdx: this._dstSheetIdx,
            dstRowStart: this._dstRowStart,
            dstColStart: this._dstColStart,
            dstRowEnd: this._dstRowEnd,
            dstColEnd: this._dstColEnd
        }
    }
}
