// DO NOT EDIT. CODE GENERATED BY gents.
export interface CellClear {
    type: 'cellClear'
    sheetIdx: number
    row: number
    col: number
}

export class CellClearBuilder {
    private _type = 'cellClear'
    private _sheetIdx!: number
    private _row!: number
    private _col!: number
    public sheetIdx(value: number) {
        this._sheetIdx = value
        return this
    }

    public row(value: number) {
        this._row = value
        return this
    }

    public col(value: number) {
        this._col = value
        return this
    }

    public build() {
        if (!this._sheetIdx) throw new Error('missing sheetIdx')
        if (!this._row) throw new Error('missing row')
        if (!this._col) throw new Error('missing col')
        return {
            type: this._type,
            sheetIdx: this._sheetIdx,
            row: this._row,
            col: this._col
        }
    }
}
