// DO NOT EDIT. CODE GENERATED BY gents.

// Take the `content` as input to the cell. The type of the `content` can be referred automatically.
export interface CellInput {
    sheetIdx: number
    row: number
    col: number
    content: string
}
