// DO NOT EDIT. CODE GENERATED BY gents.
import {BlockCellId} from './block_cell_id'
import {NormalCellId} from './normal_cell_id'

export type CellId =
    | {NormalCell: NormalCellId}
    | {BlockCell: BlockCellId}
