// DO NOT EDIT. CODE GENERATED BY gents.
import {Style} from './style'
import {Value} from './value'

export interface CellInfo {
    value: Value
    formula: string
    style: Style
    blockId?: number
}
