// DO NOT EDIT. CODE GENERATED BY gents.
import { StyleUpdateType } from './style_update_type'

export interface CellStyleUpdate {
    type: 'cellStyleUpdate'
    sheetIdx: number
    row: number
    col: number
    ty: StyleUpdateType
}

export class CellStyleUpdateBuilder {
    private _type = 'cellStyleUpdate'
    private _sheetIdx!: number
    private _row!: number
    private _col!: number
    private _ty!: StyleUpdateType
    public sheetIdx(value: number) {
        this._sheetIdx = value
        return this
    }

    public row(value: number) {
        this._row = value
        return this
    }

    public col(value: number) {
        this._col = value
        return this
    }

    public ty(value: StyleUpdateType) {
        this._ty = value
        return this
    }

    public build() {
        if (this._sheetIdx === undefined) throw new Error('missing sheetIdx')
        if (this._row === undefined) throw new Error('missing row')
        if (this._col === undefined) throw new Error('missing col')
        if (this._ty === undefined) throw new Error('missing ty')
        return {
            type: this._type,
            sheetIdx: this._sheetIdx,
            row: this._row,
            col: this._col,
            ty: this._ty
        }
    }
}
