// DO NOT EDIT. CODE GENERATED BY gents.
import {StHorizontalAlignment} from './st_horizontal_alignment'
import {StVerticalAlignment} from './st_vertical_alignment'

export interface CtCellAlignment {
    horizontal: StHorizontalAlignment | null
    vertical: StVerticalAlignment | null
    textRotation: number | null
    wrapText: boolean | null
    indent: number | null
    relativeIndent: number | null
    justifyLastLine: boolean | null
    shrinkToFit: boolean | null
    readingOrder: number | null
}
