// DO NOT EDIT. CODE GENERATED BY gents.
// Take the `content` as input to the cell. The type of the `content` can be referred automatically.
export interface CellInput {
    type: 'cellInput'
    sheetIdx: number
    row: number
    col: number
    content: string
}

export class CellInputBuilder {
    private _type = 'cellInput'
    private _sheetIdx!: number
    private _row!: number
    private _col!: number
    private _content!: string
    public sheetIdx(value: number) {
        this._sheetIdx = value
        return this
    }

    public row(value: number) {
        this._row = value
        return this
    }

    public col(value: number) {
        this._col = value
        return this
    }

    public content(value: string) {
        this._content = value
        return this
    }

    public build() {
        if (!this._sheetIdx) throw new Error('missing sheetIdx')
        if (!this._row) throw new Error('missing row')
        if (!this._col) throw new Error('missing col')
        if (!this._content) throw new Error('missing content')
        return {
            type: this._type,
            sheetIdx: this._sheetIdx,
            row: this._row,
            col: this._col,
            content: this._content
        }
    }
}
