// DO NOT EDIT. CODE GENERATED BY gents.

// Create a new block.
// 
// Note that the block id is assigned by you. You are supposed to
// manage all your blocks. If the `block id` is already existed, engines
// will remove the old one.
export interface CreateBlock {
    sheetIdx: number
    id: number
    masterRow: number
    masterCol: number
    rowCnt: number
    colCnt: number
}
