// DO NOT EDIT. CODE GENERATED BY gents.

export interface CreateAppendix {
    sheetId: number
    blockId: number
    rowIdx: number
    colIdx: number
    craftId: string
    tag: number
    content: string
}
