// DO NOT EDIT. CODE GENERATED BY gents.
// Create a new block.
//
// Note that the block id is assigned by you. You are supposed to
// manage all your blocks. If the `block id` is already existed, engines
// will remove the old one.
export interface CreateBlock {
    type: 'createBlock'
    sheetIdx: number
    id: number
    masterRow: number
    masterCol: number
    rowCnt: number
    colCnt: number
}

export class CreateBlockBuilder {
    private _type = 'createBlock'
    private _sheetIdx!: number
    private _id!: number
    private _masterRow!: number
    private _masterCol!: number
    private _rowCnt!: number
    private _colCnt!: number
    public sheetIdx(value: number) {
        this._sheetIdx = value
        return this
    }

    public id(value: number) {
        this._id = value
        return this
    }

    public masterRow(value: number) {
        this._masterRow = value
        return this
    }

    public masterCol(value: number) {
        this._masterCol = value
        return this
    }

    public rowCnt(value: number) {
        this._rowCnt = value
        return this
    }

    public colCnt(value: number) {
        this._colCnt = value
        return this
    }

    public build() {
        if (this._sheetIdx === undefined) throw new Error('missing sheetIdx')
        if (this._id === undefined) throw new Error('missing id')
        if (this._masterRow === undefined) throw new Error('missing masterRow')
        if (this._masterCol === undefined) throw new Error('missing masterCol')
        if (this._rowCnt === undefined) throw new Error('missing rowCnt')
        if (this._colCnt === undefined) throw new Error('missing colCnt')
        return {
            type: this._type,
            sheetIdx: this._sheetIdx,
            id: this._id,
            masterRow: this._masterRow,
            masterCol: this._masterCol,
            rowCnt: this._rowCnt,
            colCnt: this._colCnt
        }
    }
}
