// DO NOT EDIT. CODE GENERATED BY gents.
export interface CreateSheet {
    type: 'createSheet'
    idx: number
    newName: string
}

export class CreateSheetBuilder {
    private _type = 'createSheet'
    private _idx!: number
    private _newName!: string
    public idx(value: number) {
        this._idx = value
        return this
    }

    public newName(value: string) {
        this._newName = value
        return this
    }

    public build() {
        if (!this._idx) throw new Error('missing idx')
        if (!this._newName) throw new Error('missing newName')
        return { type: this._type, idx: this._idx, newName: this._newName }
    }
}
