// DO NOT EDIT. CODE GENERATED BY gents.
export interface DeleteRows {
    type: 'deleteRows'
    sheetIdx: number
    start: number
    count: number
}

export class DeleteRowsBuilder {
    private _type = 'deleteRows'
    private _sheetIdx!: number
    private _start!: number
    private _count!: number
    public sheetIdx(value: number) {
        this._sheetIdx = value
        return this
    }

    public start(value: number) {
        this._start = value
        return this
    }

    public count(value: number) {
        this._count = value
        return this
    }

    public build() {
        if (this._sheetIdx === undefined) throw new Error('missing sheetIdx')
        if (this._start === undefined) throw new Error('missing start')
        if (this._count === undefined) throw new Error('missing count')
        return {
            type: this._type,
            sheetIdx: this._sheetIdx,
            start: this._start,
            count: this._count
        }
    }
}
