// DO NOT EDIT. CODE GENERATED BY gents.
export interface DeleteSheet {
    type: 'deleteSheet'
    idx: number
}

export class DeleteSheetBuilder {
    private _type = 'deleteSheet'
    private _idx!: number
    public idx(value: number) {
        this._idx = value
        return this
    }

    public build() {
        if (!this._idx) throw new Error('missing idx')
        return { type: this._type, idx: this._idx }
    }
}
