// DO NOT EDIT. CODE GENERATED BY gents.
export interface DeleteColsInBlock {
    type: 'deleteColsInBlock'
    sheetIdx: number
    blockId: number
    start: number
    cnt: number
}

export class DeleteColsInBlockBuilder {
    private _type = 'deleteColsInBlock'
    private _sheetIdx!: number
    private _blockId!: number
    private _start!: number
    private _cnt!: number
    public sheetIdx(value: number) {
        this._sheetIdx = value
        return this
    }

    public blockId(value: number) {
        this._blockId = value
        return this
    }

    public start(value: number) {
        this._start = value
        return this
    }

    public cnt(value: number) {
        this._cnt = value
        return this
    }

    public build() {
        if (!this._sheetIdx) throw new Error('missing sheetIdx')
        if (!this._blockId) throw new Error('missing blockId')
        if (!this._start) throw new Error('missing start')
        if (!this._cnt) throw new Error('missing cnt')
        return {
            type: this._type,
            sheetIdx: this._sheetIdx,
            blockId: this._blockId,
            start: this._start,
            cnt: this._cnt
        }
    }
}
