// DO NOT EDIT. CODE GENERATED BY gents.
import {CellInfo} from './cell_info'
import {ColInfo} from './col_info'
import {Comment} from './comment'
import {MergeCell} from './merge_cell'
import {RowInfo} from './row_info'

export interface DisplayWindow {
    cells: readonly CellInfo[]
    rows: readonly RowInfo[]
    cols: readonly ColInfo[]
    comments: readonly Comment[]
    mergeCells: readonly MergeCell[]
}
