// DO NOT EDIT. CODE GENERATED BY gents.
import { DisplayWindow } from './display_window'

export interface DisplayWindowWithStartPoint {
    window: DisplayWindow
    startX: number
    startY: number
}
