// DO NOT EDIT. CODE GENERATED BY gents.
import { BlockInput } from './block_input'
import { BlockStyleUpdate } from './block_style_update'
import { CellClear } from './cell_clear'
import { CellFormatBrush } from './cell_format_brush'
import { CellInput } from './cell_input'
import { CellStyleUpdate } from './cell_style_update'
import { CreateAppendix } from './create_appendix'
import { CreateBlock } from './create_block'
import { CreateDiyCell } from './create_diy_cell'
import { CreateDiyCellById } from './create_diy_cell_by_id'
import { CreateSheet } from './create_sheet'
import { DeleteCols } from './delete_cols'
import { DeleteColsInBlock } from './delete_cols_in_block'
import { DeleteRows } from './delete_rows'
import { DeleteRowsInBlock } from './delete_rows_in_block'
import { DeleteSheet } from './delete_sheet'
import { EphemeralCellInput } from './ephemeral_cell_input'
import { EphemeralCellStyleUpdate } from './ephemeral_cell_style_update'
import { InsertCols } from './insert_cols'
import { InsertColsInBlock } from './insert_cols_in_block'
import { InsertRows } from './insert_rows'
import { InsertRowsInBlock } from './insert_rows_in_block'
import { LineFormatBrush } from './line_format_brush'
import { LineStyleUpdate } from './line_style_update'
import { MergeCells } from './merge_cells'
import { MoveBlock } from './move_block'
import { RemoveAppendix } from './remove_appendix'
import { RemoveBlock } from './remove_block'
import { RemoveDiyCell } from './remove_diy_cell'
import { RemoveDiyCellById } from './remove_diy_cell_by_id'
import { SetColWidth } from './set_col_width'
import { SetRowHeight } from './set_row_height'
import { SetVisible } from './set_visible'
import { SheetRename } from './sheet_rename'
import { SplitMergedCells } from './split_merged_cells'

// `EditPayload` is the basic update unit of the Workbook. Developers can config their own
// `EditAction` (e.g. setting a button to create a table) to facilitate their users.
export type EditPayload =
    | BlockInput
    | MoveBlock
    | RemoveBlock
    | CreateBlock
    | CreateDiyCell
    | CreateDiyCellById
    | RemoveDiyCell
    | RemoveDiyCellById
    | CreateAppendix
    | RemoveAppendix
    | CellStyleUpdate
    | EphemeralCellStyleUpdate
    | LineStyleUpdate
    | BlockStyleUpdate
    | CellFormatBrush
    | LineFormatBrush
    | CellInput
    | EphemeralCellInput
    | CellClear
    | SetColWidth
    | SetRowHeight
    | SetVisible
    | MergeCells
    | SplitMergedCells
    | SheetRename
    | CreateSheet
    | DeleteSheet
    | InsertCols
    | DeleteCols
    | InsertRows
    | DeleteRows
    | InsertColsInBlock
    | DeleteColsInBlock
    | InsertRowsInBlock
    | DeleteRowsInBlock
