// DO NOT EDIT. CODE GENERATED BY gents.
export interface EphemeralCellInput {
    type: 'ephemeralCellInput'
    sheetIdx: number
    id: number
    content: string
}

export class EphemeralCellInputBuilder {
    private _type = 'ephemeralCellInput'
    private _sheetIdx!: number
    private _id!: number
    private _content!: string
    public sheetIdx(value: number) {
        this._sheetIdx = value
        return this
    }

    public id(value: number) {
        this._id = value
        return this
    }

    public content(value: string) {
        this._content = value
        return this
    }

    public build() {
        if (this._sheetIdx === undefined) throw new Error('missing sheetIdx')
        if (this._id === undefined) throw new Error('missing id')
        if (this._content === undefined) throw new Error('missing content')
        return {
            type: this._type,
            sheetIdx: this._sheetIdx,
            id: this._id,
            content: this._content
        }
    }
}
