// DO NOT EDIT. CODE GENERATED BY gents.
import { StyleUpdateType } from './style_update_type'

export interface EphemeralCellStyleUpdate {
    type: 'ephemeralCellStyleUpdate'
    sheetIdx: number
    id: number
    ty: StyleUpdateType
}

export class EphemeralCellStyleUpdateBuilder {
    private _type = 'ephemeralCellStyleUpdate'
    private _sheetIdx!: number
    private _id!: number
    private _ty!: StyleUpdateType
    public sheetIdx(value: number) {
        this._sheetIdx = value
        return this
    }

    public id(value: number) {
        this._id = value
        return this
    }

    public ty(value: StyleUpdateType) {
        this._ty = value
        return this
    }

    public build() {
        if (!this._sheetIdx) throw new Error('missing sheetIdx')
        if (!this._id) throw new Error('missing id')
        if (!this._ty) throw new Error('missing ty')
        return {
            type: this._type,
            sheetIdx: this._sheetIdx,
            id: this._id,
            ty: this._ty
        }
    }
}
