// DO NOT EDIT. CODE GENERATED BY gents.
import {StyleUpdateType} from './style_update_type'

export interface EphemeralCellStyleUpdate {
    sheetIdx: number
    id: number
    ty: StyleUpdateType
}
