// DO NOT EDIT. CODE GENERATED BY gents.
export interface InsertRowsInBlock {
    type: 'insertRowsInBlock'
    sheetIdx: number
    blockId: number
    start: number
    cnt: number
}

export class InsertRowsInBlockBuilder {
    private _type = 'insertRowsInBlock'
    private _sheetIdx!: number
    private _blockId!: number
    private _start!: number
    private _cnt!: number
    public sheetIdx(value: number) {
        this._sheetIdx = value
        return this
    }

    public blockId(value: number) {
        this._blockId = value
        return this
    }

    public start(value: number) {
        this._start = value
        return this
    }

    public cnt(value: number) {
        this._cnt = value
        return this
    }

    public build() {
        if (this._sheetIdx === undefined) throw new Error('missing sheetIdx')
        if (this._blockId === undefined) throw new Error('missing blockId')
        if (this._start === undefined) throw new Error('missing start')
        if (this._cnt === undefined) throw new Error('missing cnt')
        return {
            type: this._type,
            sheetIdx: this._sheetIdx,
            blockId: this._blockId,
            start: this._start,
            cnt: this._cnt
        }
    }
}
