// DO NOT EDIT. CODE GENERATED BY gents.
export interface InsertRows {
    type: 'insertRows'
    sheetIdx: number
    start: number
    count: number
}

export class InsertRowsBuilder {
    private _type = 'insertRows'
    private _sheetIdx!: number
    private _start!: number
    private _count!: number
    public sheetIdx(value: number) {
        this._sheetIdx = value
        return this
    }

    public start(value: number) {
        this._start = value
        return this
    }

    public count(value: number) {
        this._count = value
        return this
    }

    public build() {
        if (!this._sheetIdx) throw new Error('missing sheetIdx')
        if (!this._start) throw new Error('missing start')
        if (!this._count) throw new Error('missing count')
        return {
            type: this._type,
            sheetIdx: this._sheetIdx,
            start: this._start,
            count: this._count
        }
    }
}
