// DO NOT EDIT. CODE GENERATED BY gents.
import { StyleUpdateType } from './style_update_type'

export interface LineStyleUpdate {
    type: 'lineStyleUpdate'
    sheetIdx: number
    from: number
    to: number
    ty: StyleUpdateType
    row: boolean
}

export class LineStyleUpdateBuilder {
    private _type = 'lineStyleUpdate'
    private _sheetIdx!: number
    private _from!: number
    private _to!: number
    private _ty!: StyleUpdateType
    private _row!: boolean
    public sheetIdx(value: number) {
        this._sheetIdx = value
        return this
    }

    public from(value: number) {
        this._from = value
        return this
    }

    public to(value: number) {
        this._to = value
        return this
    }

    public ty(value: StyleUpdateType) {
        this._ty = value
        return this
    }

    public row(value: boolean) {
        this._row = value
        return this
    }

    public build() {
        if (this._sheetIdx === undefined) throw new Error('missing sheetIdx')
        if (this._from === undefined) throw new Error('missing from')
        if (this._to === undefined) throw new Error('missing to')
        if (this._ty === undefined) throw new Error('missing ty')
        if (this._row === undefined) throw new Error('missing row')
        return {
            type: this._type,
            sheetIdx: this._sheetIdx,
            from: this._from,
            to: this._to,
            ty: this._ty,
            row: this._row
        }
    }
}
