// DO NOT EDIT. CODE GENERATED BY gents.
import {StyleUpdateType} from './style_update_type'

export interface LineStyleUpdate {
    sheetIdx: number
    from: number
    to: number
    ty: StyleUpdateType
    row: boolean
}
