// DO NOT EDIT. CODE GENERATED BY gents.

export interface LineFormatBrush {
    srcSheetIdx: number
    srcRow: number
    srcCol: number
    dstSheetIdx: number
    row: boolean
    from: number
    to: number
}
