// DO NOT EDIT. CODE GENERATED BY gents.
export interface LineFormatBrush {
    type: 'lineFormatBrush'
    srcSheetIdx: number
    srcRow: number
    srcCol: number
    dstSheetIdx: number
    row: boolean
    from: number
    to: number
}

export class LineFormatBrushBuilder {
    private _type = 'lineFormatBrush'
    private _srcSheetIdx!: number
    private _srcRow!: number
    private _srcCol!: number
    private _dstSheetIdx!: number
    private _row!: boolean
    private _from!: number
    private _to!: number
    public srcSheetIdx(value: number) {
        this._srcSheetIdx = value
        return this
    }

    public srcRow(value: number) {
        this._srcRow = value
        return this
    }

    public srcCol(value: number) {
        this._srcCol = value
        return this
    }

    public dstSheetIdx(value: number) {
        this._dstSheetIdx = value
        return this
    }

    public row(value: boolean) {
        this._row = value
        return this
    }

    public from(value: number) {
        this._from = value
        return this
    }

    public to(value: number) {
        this._to = value
        return this
    }

    public build() {
        if (!this._srcSheetIdx) throw new Error('missing srcSheetIdx')
        if (!this._srcRow) throw new Error('missing srcRow')
        if (!this._srcCol) throw new Error('missing srcCol')
        if (!this._dstSheetIdx) throw new Error('missing dstSheetIdx')
        if (!this._row) throw new Error('missing row')
        if (!this._from) throw new Error('missing from')
        if (!this._to) throw new Error('missing to')
        return {
            type: this._type,
            srcSheetIdx: this._srcSheetIdx,
            srcRow: this._srcRow,
            srcCol: this._srcCol,
            dstSheetIdx: this._dstSheetIdx,
            row: this._row,
            from: this._from,
            to: this._to
        }
    }
}
