// DO NOT EDIT. CODE GENERATED BY gents.
export interface MergeCells {
    type: 'mergeCells'
    sheetIdx: number
    startRow: number
    startCol: number
    endRow: number
    endCol: number
}

export class MergeCellsBuilder {
    private _type = 'mergeCells'
    private _sheetIdx!: number
    private _startRow!: number
    private _startCol!: number
    private _endRow!: number
    private _endCol!: number
    public sheetIdx(value: number) {
        this._sheetIdx = value
        return this
    }

    public startRow(value: number) {
        this._startRow = value
        return this
    }

    public startCol(value: number) {
        this._startCol = value
        return this
    }

    public endRow(value: number) {
        this._endRow = value
        return this
    }

    public endCol(value: number) {
        this._endCol = value
        return this
    }

    public build() {
        if (!this._sheetIdx) throw new Error('missing sheetIdx')
        if (!this._startRow) throw new Error('missing startRow')
        if (!this._startCol) throw new Error('missing startCol')
        if (!this._endRow) throw new Error('missing endRow')
        if (!this._endCol) throw new Error('missing endCol')
        return {
            type: this._type,
            sheetIdx: this._sheetIdx,
            startRow: this._startRow,
            startCol: this._startCol,
            endRow: this._endRow,
            endCol: this._endCol
        }
    }
}
