// DO NOT EDIT. CODE GENERATED BY gents.
import { WorkbookFile } from './workbook_file'

// Join to edit the file.
export interface Join {
    file: string
    user: string
    wbFile?: WorkbookFile
}
