// DO NOT EDIT. CODE GENERATED BY gents.
import {Color} from './color'
import {StPatternType} from './st_pattern_type'

export interface PatternFill {
    fgColor: Color | null
    bgColor: Color | null
    patternType: StPatternType | null
}
