// DO NOT EDIT. CODE GENERATED BY gents.
export interface RemoveDiyCell {
    type: 'removeDiyCell'
    sheetIdx: number
    row: number
    col: number
}

export class RemoveDiyCellBuilder {
    private _type = 'removeDiyCell'
    private _sheetIdx!: number
    private _row!: number
    private _col!: number
    public sheetIdx(value: number) {
        this._sheetIdx = value
        return this
    }

    public row(value: number) {
        this._row = value
        return this
    }

    public col(value: number) {
        this._col = value
        return this
    }

    public build() {
        if (this._sheetIdx === undefined) throw new Error('missing sheetIdx')
        if (this._row === undefined) throw new Error('missing row')
        if (this._col === undefined) throw new Error('missing col')
        return {
            type: this._type,
            sheetIdx: this._sheetIdx,
            row: this._row,
            col: this._col
        }
    }
}
