// DO NOT EDIT. CODE GENERATED BY gents.
export interface RemoveBlock {
    type: 'removeBlock'
    sheetIdx: number
    id: number
}

export class RemoveBlockBuilder {
    private _type = 'removeBlock'
    private _sheetIdx!: number
    private _id!: number
    public sheetIdx(value: number) {
        this._sheetIdx = value
        return this
    }

    public id(value: number) {
        this._id = value
        return this
    }

    public build() {
        if (this._sheetIdx === undefined) throw new Error('missing sheetIdx')
        if (this._id === undefined) throw new Error('missing id')
        return { type: this._type, sheetIdx: this._sheetIdx, id: this._id }
    }
}
