// DO NOT EDIT. CODE GENERATED BY gents.
export interface RemoveAppendix {
    type: 'removeAppendix'
    sheetId?: number
    sheetIdx?: number
    blockId: number
    rowIdx: number
    colIdx: number
}

export class RemoveAppendixBuilder {
    private _type = 'removeAppendix'
    private _sheetId?: number
    private _sheetIdx?: number
    private _blockId!: number
    private _rowIdx!: number
    private _colIdx!: number
    public sheetId(value: number) {
        this._sheetId = value
        return this
    }

    public sheetIdx(value: number) {
        this._sheetIdx = value
        return this
    }

    public blockId(value: number) {
        this._blockId = value
        return this
    }

    public rowIdx(value: number) {
        this._rowIdx = value
        return this
    }

    public colIdx(value: number) {
        this._colIdx = value
        return this
    }

    public build() {
        if (this._blockId === undefined) throw new Error('missing blockId')
        if (this._rowIdx === undefined) throw new Error('missing rowIdx')
        if (this._colIdx === undefined) throw new Error('missing colIdx')
        return {
            type: this._type,
            sheetId: this._sheetId,
            sheetIdx: this._sheetIdx,
            blockId: this._blockId,
            rowIdx: this._rowIdx,
            colIdx: this._colIdx
        }
    }
}
