// DO NOT EDIT. CODE GENERATED BY gents.
export interface SetColWidth {
    type: 'setColWidth'
    sheetIdx: number
    col: number
    width: number
}

export class SetColWidthBuilder {
    private _type = 'setColWidth'
    private _sheetIdx!: number
    private _col!: number
    private _width!: number
    public sheetIdx(value: number) {
        this._sheetIdx = value
        return this
    }

    public col(value: number) {
        this._col = value
        return this
    }

    public width(value: number) {
        this._width = value
        return this
    }

    public build() {
        if (this._sheetIdx === undefined) throw new Error('missing sheetIdx')
        if (this._col === undefined) throw new Error('missing col')
        if (this._width === undefined) throw new Error('missing width')
        return {
            type: this._type,
            sheetIdx: this._sheetIdx,
            col: this._col,
            width: this._width
        }
    }
}
