// DO NOT EDIT. CODE GENERATED BY gents.
export interface SetVisible {
    type: 'setVisible'
    isRow: boolean
    sheetIdx: number
    start: number
    visible: boolean
}

export class SetVisibleBuilder {
    private _type = 'setVisible'
    private _isRow!: boolean
    private _sheetIdx!: number
    private _start!: number
    private _visible!: boolean
    public isRow(value: boolean) {
        this._isRow = value
        return this
    }

    public sheetIdx(value: number) {
        this._sheetIdx = value
        return this
    }

    public start(value: number) {
        this._start = value
        return this
    }

    public visible(value: boolean) {
        this._visible = value
        return this
    }

    public build() {
        if (!this._isRow) throw new Error('missing isRow')
        if (!this._sheetIdx) throw new Error('missing sheetIdx')
        if (!this._start) throw new Error('missing start')
        if (!this._visible) throw new Error('missing visible')
        return {
            type: this._type,
            isRow: this._isRow,
            sheetIdx: this._sheetIdx,
            start: this._start,
            visible: this._visible
        }
    }
}
