// DO NOT EDIT. CODE GENERATED BY gents.
export interface SetRowHeight {
    type: 'setRowHeight'
    sheetIdx: number
    row: number
    height: number
}

export class SetRowHeightBuilder {
    private _type = 'setRowHeight'
    private _sheetIdx!: number
    private _row!: number
    private _height!: number
    public sheetIdx(value: number) {
        this._sheetIdx = value
        return this
    }

    public row(value: number) {
        this._row = value
        return this
    }

    public height(value: number) {
        this._height = value
        return this
    }

    public build() {
        if (this._sheetIdx === undefined) throw new Error('missing sheetIdx')
        if (this._row === undefined) throw new Error('missing row')
        if (this._height === undefined) throw new Error('missing height')
        return {
            type: this._type,
            sheetIdx: this._sheetIdx,
            row: this._row,
            height: this._height
        }
    }
}
