// DO NOT EDIT. CODE GENERATED BY gents.

// Find a sheet by its name and rename it. If no sheet is found, do nothing.
export interface SheetRename {
    oldName: string | null
    idx: number | null
    newName: string
}
