// DO NOT EDIT. CODE GENERATED BY gents.
// Find a sheet by its name and rename it. If no sheet is found, do nothing.
export interface SheetRename {
    type: 'sheetRename'
    oldName?: string
    idx?: number
    newName: string
}

export class SheetRenameBuilder {
    private _type = 'sheetRename'
    private _oldName?: string
    private _idx?: number
    private _newName!: string
    public oldName(value: string) {
        this._oldName = value
        return this
    }

    public idx(value: number) {
        this._idx = value
        return this
    }

    public newName(value: string) {
        this._newName = value
        return this
    }

    public build() {
        if (!this._newName) throw new Error('missing newName')
        return {
            type: this._type,
            oldName: this._oldName,
            idx: this._idx,
            newName: this._newName
        }
    }
}
