// DO NOT EDIT. CODE GENERATED BY gents.

// 18.18.40
export type StHorizontalAlignment =
    | 'general'
    | 'left'
    | 'center'
    | 'right'
    | 'fill'
    | 'justify'
    | 'centerContinuous'
    | 'distributed'
