// DO NOT EDIT. CODE GENERATED BY gents.
import { Alignment } from './alignment'
import { Border } from './border'
import { CtCellProtection } from './cell_protection'
import { Fill } from './fill'
import { Font } from './font'

export interface Style {
    font: Font
    fill: Fill
    border: Border
    alignment?: Alignment
    protection?: CtCellProtection
    formatter: string
}
