// DO NOT EDIT. CODE GENERATED BY gents.
import {Border} from './border'
import {CtCellAlignment} from './cell_alignment'
import {CtCellProtection} from './cell_protection'
import {Fill} from './fill'
import {Font} from './font'

export interface Style {
    font: Font
    fill: Fill
    border: Border
    alignment: CtCellAlignment | null
    protection: CtCellProtection | null
    formatter: string
}
