// DO NOT EDIT. CODE GENERATED BY gents.
import { Alignment } from './alignment'
import { PatternFill } from './pattern_fill'
import { StBorderStyle } from './st_border_style'
import { StUnderlineValues } from './st_underline_values'

export interface StyleUpdateType {
    setFontBold?: boolean
    setFontItalic?: boolean
    setFontUnderline?: StUnderlineValues
    setFontColor?: string
    setFontSize?: number
    setFontName?: string
    setFontOutline?: boolean
    setFontShadow?: boolean
    setFontStrike?: boolean
    setFontCondense?: boolean
    setLeftBorderColor?: string
    setRightBorderColor?: string
    setTopBorderColor?: string
    setBottomBorderColor?: string
    setLeftBorderStyle?: StBorderStyle
    setRightBorderStyle?: StBorderStyle
    setTopBorderStyle?: StBorderStyle
    setBottomBorderStyle?: StBorderStyle
    setBorderGiagonalUp?: boolean
    setBorderGiagonalDown?: boolean
    setBorderOutline?: boolean
    setPatternFill?: PatternFill
    setAlignment?: Alignment
}

export class StyleUpdateTypeBuilder {
    private _setFontBold?: boolean
    private _setFontItalic?: boolean
    private _setFontUnderline?: StUnderlineValues
    private _setFontColor?: string
    private _setFontSize?: number
    private _setFontName?: string
    private _setFontOutline?: boolean
    private _setFontShadow?: boolean
    private _setFontStrike?: boolean
    private _setFontCondense?: boolean
    private _setLeftBorderColor?: string
    private _setRightBorderColor?: string
    private _setTopBorderColor?: string
    private _setBottomBorderColor?: string
    private _setLeftBorderStyle?: StBorderStyle
    private _setRightBorderStyle?: StBorderStyle
    private _setTopBorderStyle?: StBorderStyle
    private _setBottomBorderStyle?: StBorderStyle
    private _setBorderGiagonalUp?: boolean
    private _setBorderGiagonalDown?: boolean
    private _setBorderOutline?: boolean
    private _setPatternFill?: PatternFill
    private _setAlignment?: Alignment
    public setFontBold(value: boolean) {
        this._setFontBold = value
        return this
    }

    public setFontItalic(value: boolean) {
        this._setFontItalic = value
        return this
    }

    public setFontUnderline(value: StUnderlineValues) {
        this._setFontUnderline = value
        return this
    }

    public setFontColor(value: string) {
        this._setFontColor = value
        return this
    }

    public setFontSize(value: number) {
        this._setFontSize = value
        return this
    }

    public setFontName(value: string) {
        this._setFontName = value
        return this
    }

    public setFontOutline(value: boolean) {
        this._setFontOutline = value
        return this
    }

    public setFontShadow(value: boolean) {
        this._setFontShadow = value
        return this
    }

    public setFontStrike(value: boolean) {
        this._setFontStrike = value
        return this
    }

    public setFontCondense(value: boolean) {
        this._setFontCondense = value
        return this
    }

    public setLeftBorderColor(value: string) {
        this._setLeftBorderColor = value
        return this
    }

    public setRightBorderColor(value: string) {
        this._setRightBorderColor = value
        return this
    }

    public setTopBorderColor(value: string) {
        this._setTopBorderColor = value
        return this
    }

    public setBottomBorderColor(value: string) {
        this._setBottomBorderColor = value
        return this
    }

    public setLeftBorderStyle(value: StBorderStyle) {
        this._setLeftBorderStyle = value
        return this
    }

    public setRightBorderStyle(value: StBorderStyle) {
        this._setRightBorderStyle = value
        return this
    }

    public setTopBorderStyle(value: StBorderStyle) {
        this._setTopBorderStyle = value
        return this
    }

    public setBottomBorderStyle(value: StBorderStyle) {
        this._setBottomBorderStyle = value
        return this
    }

    public setBorderGiagonalUp(value: boolean) {
        this._setBorderGiagonalUp = value
        return this
    }

    public setBorderGiagonalDown(value: boolean) {
        this._setBorderGiagonalDown = value
        return this
    }

    public setBorderOutline(value: boolean) {
        this._setBorderOutline = value
        return this
    }

    public setPatternFill(value: PatternFill) {
        this._setPatternFill = value
        return this
    }

    public setAlignment(value: Alignment) {
        this._setAlignment = value
        return this
    }

    public build() {
        return {
            setFontBold: this._setFontBold,
            setFontItalic: this._setFontItalic,
            setFontUnderline: this._setFontUnderline,
            setFontColor: this._setFontColor,
            setFontSize: this._setFontSize,
            setFontName: this._setFontName,
            setFontOutline: this._setFontOutline,
            setFontShadow: this._setFontShadow,
            setFontStrike: this._setFontStrike,
            setFontCondense: this._setFontCondense,
            setLeftBorderColor: this._setLeftBorderColor,
            setRightBorderColor: this._setRightBorderColor,
            setTopBorderColor: this._setTopBorderColor,
            setBottomBorderColor: this._setBottomBorderColor,
            setLeftBorderStyle: this._setLeftBorderStyle,
            setRightBorderStyle: this._setRightBorderStyle,
            setTopBorderStyle: this._setTopBorderStyle,
            setBottomBorderStyle: this._setBottomBorderStyle,
            setBorderGiagonalUp: this._setBorderGiagonalUp,
            setBorderGiagonalDown: this._setBorderGiagonalDown,
            setBorderOutline: this._setBorderOutline,
            setPatternFill: this._setPatternFill,
            setAlignment: this._setAlignment
        }
    }
}
