// DO NOT EDIT. CODE GENERATED BY gents.

export type WorkbookUpdateType =
    | 'doNothing'
    | 'cell'
    | 'sheet'
    | 'sheetAndCell'
    | 'undoNothing'
    | 'redoNothing'
    | 'undo'
    | 'redo'
