// DO NOT EDIT. CODE GENERATED BY gents.
import {Task} from './task'

// `ActionEffect` represents the result of handling `EditAction`.
// `version` would be increased if the action is successfully handled.
// 
// What's more, since `LogiSheets` provides developers with the ability
// of developing their own functions, in these cases, `engine` will not know
// how to compute them and just return it the JS side.
export interface ActionEffect {
    version: number
    asyncTasks: readonly Task[]
}
