// DO NOT EDIT. CODE GENERATED BY gents.
import {StHorizontalAlignment} from './st_horizontal_alignment'
import {StVerticalAlignment} from './st_vertical_alignment'

export interface CtCellAlignment {
    horizontal?: StHorizontalAlignment
    vertical?: StVerticalAlignment
    textRotation?: number
    wrapText?: boolean
    indent?: number
    relativeIndent?: number
    justifyLastLine?: boolean
    shrinkToFit?: boolean
    readingOrder?: number
}
