// DO NOT EDIT. CODE GENERATED BY gents.
import {PayloadsAction} from './payloads_action'

// `EditAction` represents your update behavior to the workbook.
export type EditAction =
    | 'Undo'
    | 'Redo'
    | {Payloads: PayloadsAction}
