// DO NOT EDIT. CODE GENERATED BY gents.
import {GradientFill} from './gradient_fill'
import {PatternFill} from './pattern_fill'

export type Fill =
    | {patternFill: PatternFill}
    | {gradientFill: GradientFill}
