// DO NOT EDIT. CODE GENERATED BY gents.
import {Color} from './color'
import {CtFontFamily} from './font_family'
import {CtFontName} from './font_name'
import {CtFontScheme} from './font_scheme'
import {CtUnderlineProperty} from './underline_property'
import {CtVerticalAlignFontProperty} from './vertical_align_font_property'

export interface Font {
    bold: boolean
    italic: boolean
    underline: CtUnderlineProperty | null
    color: Color | null
    sz: number | null
    name: CtFontName | null
    charset: number | null
    family: CtFontFamily | null
    strike: boolean
    outline: boolean
    shadow: boolean
    condense: boolean
    extend: boolean
    vertAlign: CtVerticalAlignFontProperty | null
    scheme: CtFontScheme | null
}
