// DO NOT EDIT. CODE GENERATED BY gents.
import {GradientStop} from './gradient_stop'
import {StGradientType} from './st_gradient_type'

export interface GradientFill {
    stops: readonly GradientStop[]
    ty: StGradientType
    degree: number
    left: number
    right: number
    top: number
    bottom: number
}
