// DO NOT EDIT. CODE GENERATED BY gents.

// If users' action is conflicted with others', this action will not be executed
// and this message will be sent to this user only.
export interface SequencerActionInvalidMessage {
    version: number
    userId: string
    fileId: string
    reason: string
}
