// DO NOT EDIT. CODE GENERATED BY gents.
import {BlockInput} from './block_input'
import {BlockStyleUpdate} from './block_style_update'
import {CellInput} from './cell_input'
import {ColShift} from './col_shift'
import {CreateBlock} from './create_block'
import {LineShiftInBlock} from './line_shift_in_block'
import {MoveBlock} from './move_block'
import {RowShift} from './row_shift'
import {SetColWidth} from './set_col_width'
import {SetRowHeight} from './set_row_height'
import {SetVisible} from './set_visible'
import {SheetRename} from './sheet_rename'
import {SheetShift} from './sheet_shift.tx'
import {StyleUpdate} from './style_update'

export type EditPayload =
    | {BlockInput: BlockInput}
    | {BlockStyleUpdate: BlockStyleUpdate}
    | {CellInput: CellInput}
    | {ColShift: ColShift}
    | {CreateBlock: CreateBlock}
    | {LineShiftInBlock: LineShiftInBlock}
    | {MoveBlock: MoveBlock}
    | {RowShift: RowShift}
    | {SetColWidth: SetColWidth}
    | {SetRowHeight: SetRowHeight}
    | {StyleUpdate: StyleUpdate}
    | {SheetRename: SheetRename}
    | {SetVisible: SetVisible}
    | {SheetShift: SheetShift}
