// DO NOT EDIT. CODE GENERATED BY gents.

export type StBorderStyle =
    | 'None'
    | 'Thin'
    | 'Medium'
    | 'Dashed'
    | 'Dotted'
    | 'Thick'
    | 'Double'
    | 'Hair'
    | 'MediumDashed'
    | 'DashDot'
    | 'MediumDashDot'
    | 'DashDotDot'
    | 'MediumDashDotDot'
    | 'SlantDashDot'
