// DO NOT EDIT. CODE GENERATED BY gents.

export type StHorizontalAlignment =
    | 'General'
    | 'Left'
    | 'Center'
    | 'Right'
    | 'Fill'
    | 'Justify'
    | 'CenterContinuous'
    | 'Distributed'
