// DO NOT EDIT. CODE GENERATED BY gents.

// 18.18.55
export type StPatternType =
    | 'none'
    | 'solid'
    | 'mediumGray'
    | 'darkGray'
    | 'lightGray'
    | 'darkHorizontal'
    | 'darkVertical'
    | 'darkDown'
    | 'darkUp'
    | 'darkGrid'
    | 'darkTrellis'
    | 'lightHorizontal'
    | 'lightVertical'
    | 'lightDown'
    | 'lightUp'
    | 'lightGrid'
    | 'lightTrellis'
    | 'gray125'
    | 'gray0625'
