// DO NOT EDIT. CODE GENERATED BY gents.
import {StUnderlineValues} from './st_underline_values'
import {StBorderStyle} from './st_border_style'
import {PatternFill} from './pattern_fill'

export interface StyleUpdateType {
    setFontBold?: boolean
    setFontItalic?: boolean
    setFontUnderline?: StUnderlineValues
    setFontColor?: string
    setFontSize?: number
    setFontName?: string
    setFontOutline?: boolean
    setFontShadow?: boolean
    setFontStrike?: boolean
    setFontCondense?: boolean
    setLeftBorderColor?: string
    setRightBorderColor?: string
    setTopBorderColor?: string
    setBottomBorderColor?: string
    setLeftBorderStyle?: StBorderStyle
    setRightBorderStyle?: StBorderStyle
    setTopBorderStyle?: StBorderStyle
    setBottomBorderStyle?: StBorderStyle
    setBorderGiagonalUp?: boolean
    setBorderGiagonalDown?: boolean
    setPatternFill?: PatternFill
}
