// DO NOT EDIT. CODE GENERATED BY gents.
import {Font} from './font'
import {Fill} from './fill'
import {CtCellProtection} from './cell_protection'
import {Border} from './border'
import {CtCellAlignment} from './cell_alignment'

export interface Style {
    font: Font
    fill: Fill
    border: Border
    alignment?: CtCellAlignment
    protection?: CtCellProtection
    formatter: string
}
