/**
 * The capability manifest generated by `craftsmith build` (dist/manifest.json).
 *
 * This is the contract Watson reads to discover a craft's skill and invoke its
 * tools. It is a BUILD ARTIFACT: generated from `tools.ts`, committed, verified
 * clean in CI, never hand-edited — the single source of truth is the code.
 *
 * See docs/craft/craftsmith.md.
 */

/** JSON Schema draft-07 subset — structurally compatible with logician's. */
export interface JSONSchema {
    type?: string | string[]
    description?: string
    properties?: Record<string, JSONSchema>
    required?: string[]
    items?: JSONSchema
    enum?: (string | number)[]
    [k: string]: unknown
}

/** Whether/how a tool mutates workbook state. */
export type MutatesPolicy = 'none' | 'temp' | true

/** Confirmation policy — mirrors logician's ConfirmationPolicy. */
export type ConfirmationPolicy = 'never' | 'once' | 'always' | 'destructive'

export interface ManifestTool {
    /** LLM-facing tool id (snake_case, no "__"). */
    name: string
    /** One-line description; the model uses this to decide when to call. */
    description: string
    /** JSON Schema for the argument object the LLM produces. */
    inputSchema: JSONSchema
    /** Best-effort schema of the return value (documentation only; Anthropic
     *  tool defs carry no output schema). Omitted if not serializable. */
    outputSchema?: JSONSchema
    /** Parameter names in call order — used to turn the LLM's arg object back
     *  into positional arguments: fn(ctx, ...paramOrder.map(p => args[p])). */
    paramOrder: string[]
    /** Module the function lives in, relative to the package root (e.g. "tools.js"). */
    entry: string
    /** Exported binding name = the dispatch key. */
    export: string
    /** Whether/how the tool mutates the workbook. Default 'none'. */
    mutates: MutatesPolicy
    /** Confirmation policy. Default 'never'. */
    confirmation: ConfirmationPolicy
}

export interface ManifestSkill {
    /** "When to use this craft" — what Watson sees at discover time. */
    description: string
    /** Optional prompt fragment injected once Watson decides to use the craft. */
    guidance?: string
}

export interface CraftManifest {
    schemaVersion: 1
    craftId: string
    version: string
    label: string
    /** Present iff the craft has an index.html. Package-relative. */
    url?: string
    /** Present iff the craft has a runtime.ts (CraftRuntime lifecycle). */
    rtJs?: string
    /** Present iff the craft exposes tools (has a tools.ts with @logicianSkill). */
    skill?: ManifestSkill
    /** One per @tool. Empty/absent for UI-only crafts. */
    tools?: ManifestTool[]
}
