/**
 * The capability manifest generated by `craftsmith build` (dist/manifest.json).
 *
 * This is the contract Watson reads to discover a craft's skill and invoke its
 * tools. It is a BUILD ARTIFACT: generated from `tools.ts` and package.json,
 * never hand-edited — the single source of truth is the code. It lives in the
 * craft's gitignored dist/ and is not committed; `craftsmith check` is the
 * gate that keeps the source extractable.
 *
 * Consumer: logisheets-logician, which mirrors these types in
 * packages/logician/src/crafts/manifest.ts — change both together.
 *
 * Shape guarantees from the extractor: optional keys are absent from the written
 * JSON rather than empty; `tools` / `roles` are in source order; tool and
 * role names are unique within a craft (duplicates are check errors).
 *
 * See docs/craft/writing-a-craft.md.
 */

/** JSON Schema draft-07 subset — structurally compatible with logician's. */
export interface JSONSchema {
    type?: string | string[]
    description?: string
    properties?: Record<string, JSONSchema>
    required?: string[]
    items?: JSONSchema
    enum?: (string | number)[]
    [k: string]: unknown
}

/**
 * Whether/how a tool mutates workbook state, from `@mutates`. logician
 * currently treats `'temp'` and `true` alike, as mutating.
 */
export type MutatesPolicy = 'none' | 'temp' | true

/** Confirmation policy — mirrors logician's ConfirmationPolicy. */
export type ConfirmationPolicy = 'never' | 'once' | 'always' | 'destructive'

export interface ManifestTool {
    /**
     * LLM-facing tool id: the export name converted camelCase → snake_case.
     * logician namespaces it per craft (`<craftId>__<name>`), so it should not
     * contain "__" — this is NOT validated.
     */
    name: string
    /**
     * The `@tool` text, whitespace collapsed to one line; the model uses this
     * to decide when to call. Empty only alongside a check error.
     */
    description: string
    /**
     * JSON Schema for the argument object the LLM produces: always
     * `type: 'object'`, one property per parameter after `ctx`, `required`
     * listing the non-optional ones (omitted when none are).
     */
    inputSchema: JSONSchema
    /** Best-effort schema of the return value (documentation only; Anthropic
     *  tool defs carry no output schema). Omitted if not serializable. */
    outputSchema?: JSONSchema
    /** Parameter names in call order — used to turn the LLM's arg object back
     *  into positional arguments: fn(ctx, ...paramOrder.map(p => args[p])). */
    paramOrder: string[]
    /** Module the function lives in, relative to the package root (e.g. "tools.js"). */
    entry: string
    /** Exported binding name = the dispatch key. */
    export: string
    /** Whether/how the tool mutates the workbook. Default 'none'. */
    mutates: MutatesPolicy
    /**
     * Confirmation policy from `@confirm`. When absent (or unrecognized) it
     * defaults to 'never' for a `mutates: 'none'` tool and 'always' otherwise.
     */
    confirmation: ConfirmationPolicy
}

/**
 * From the first `/** … *␟/` block in tools.ts that carries
 * `@logicianSkill` (later ones are ignored). Both texts are whitespace-
 * collapsed to a single line.
 */
export interface ManifestSkill {
    /** "When to use this craft" — what Watson sees at discover time. */
    description: string
    /** Optional prompt fragment injected once Watson decides to use the craft. */
    guidance?: string
}

/**
 * One question this craft can put to a model — the craft→AI direction.
 *
 * A `@tool` is "the AI calls the craft with this schema"; a role is "the craft
 * asks, and the model answers with this schema", reading whatever it needs
 * through the craft's own read-only tools on the way.
 */
export interface ManifestRole {
    /** The name `craftAi.ask(role, …)` selects. Kebab-case (validated). */
    name: string
    /**
     * System prompt from `@system`, sent verbatim — except that, like every
     * JSDoc text the extractor reads, its whitespace is collapsed to single
     * spaces (line breaks and indentation do not survive).
     *
     * The one manifest field not derived from a signature: a prompt has no code
     * form, so nothing can check it against reality. It is declared rather than
     * passed at call time so the consent prompt can show the user exactly what
     * the craft will say.
     */
    system: string
    /** JSON Schema the reply must satisfy, from the annotated declaration. */
    replySchema: JSONSchema
    /** That declaration's exported name, for the generated role→type map. */
    replyType: string
}

export interface CraftManifest {
    schemaVersion: 1
    /**
     * package.json `craftId`, else `name`. Kebab-case is enforced only for
     * an explicit `craftId`.
     */
    craftId: string
    /** package.json `version`, default '0.0.0'. */
    version: string
    /** package.json `label`, else `name`, else the craftId. */
    label: string
    /** Present iff the craft has an index.html. Package-relative. */
    url?: string
    /** Present iff the craft has a runtime.ts (CraftRuntime lifecycle). */
    rtJs?: string
    /**
     * Present iff tools.ts has a `@logicianSkill` block. A craft with tools
     * but no skill fails check; a skill without tools is allowed.
     */
    skill?: ManifestSkill
    /** One per @tool. Empty/absent for UI-only crafts. */
    tools?: ManifestTool[]
    /**
     * One per @aiRole. Its presence is what permits `craftAi.ask`. Check
     * requires at least one `mutates: 'none'` tool alongside it.
     */
    roles?: ManifestRole[]
}
