[package]
name = "logisheets_lexer"
description = "Lexer for Excel formulas, used by the LogiSheets spreadsheet engine."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
pest = { workspace = true }
pest_derive = { workspace = true }
tracing = "0.1"
