[package]
name = "logisheets_workbook"
description = "Read and write .xlsx (Excel / OOXML) files for LogiSheets."
authors.workspace = true
edition.workspace = true
version.workspace = true
license.workspace = true
repository = "https://github.com/logisky/LogiSheets"
keywords = ["excel", "xlsx", "ooxml", "spreadsheet", "parser"]

[dependencies]
regex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
zip = { version = "0.6.0", default-features = false, features = ["deflate"] }
gents = { workspace = true }
gents_derives = { workspace = true }
xmlserde = { workspace = true }
xmlserde_derives = { workspace = true }

logisheets_workbook_derives = { workspace = true }

[dev-dependencies]
xmldiff = { workspace = true }
