[package]
name = "logisheets_lexer4fmt"
description = "Excel formula lexer for LogiSheets, specialized for formula display and autocomplete suggestions."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
pest = { workspace = true }
pest_derive = { workspace = true }
tracing = "0.1"

gents = { workspace = true }
gents_derives = { workspace = true }
serde = { workspace = true }
