[package]
name = "logisheets_formatter"
description = "LogiSheets Custom Number Formatter"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
lazy_static = { workspace = true }
regex = { workspace = true }
