name: rust test

on: [pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose --workspace --locked
      - name: Run tests
        run: cargo test --verbose --workspace --locked

      - name: generate bindings and ensure clean
        run: cargo run --package buildtools --bin generate --all-features
      - uses: numtide/clean-git-action@v1

      - name: Test using Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install and build (JS / WASM)
        run: ./scripts/ci-build.sh

      - name: Test logisheets-web and logisheets-core
        run: |
          yarn workspace logisheets-web test
          yarn workspace logisheets-core test

      - name: Install Playwright browser
        run: yarn playwright install --with-deps chromium
      - name: Run engine UI e2e tests
        run: yarn test:e2e

      - name: Test logisheets-node
        run: yarn workspace logisheets test

      - name: Test logisheets-runtime
        run: yarn workspace logisheets-runtime test
