name: rust test

on: [pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose --workspace --locked
      - name: Run tests
        run: cargo test --verbose --workspace --locked

      - name: generate bindings and ensure clean
        run: cargo run --package buildtools --bin generate --all-features
      - uses: numtide/clean-git-action@v1

      - name: Test using Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - run: yarn install && cargo install --locked wasm-pack
      - run: yarn workspace logisheets-web build
      - run: yarn workspace logisheets-web test
      - run: yarn workspace logisheets-core build
      - run: yarn workspace logisheets-core test
      - run: yarn workspace logician build
      - run: yarn run run-scripts && yarn run wasm
      - run: yarn workspace logisheets-engine build
      - run: yarn build

      - name: Build and test logisheets-node
        run: |
          yarn workspace logisheets run link
          yarn workspace logisheets build
          yarn workspace logisheets test

      - name: Build and test logisheets-runtime
        run: |
          yarn workspace logisheets-runtime build
          yarn workspace logisheets-runtime test
